-- gdelt_volume_query.sql
-- Produces gdelt_volume.csv: 12-month GDELT news-mention volume per fighter.
-- Source: gdelt-bq.gdeltv2.gkg_partitioned (BigQuery public dataset).
-- Window: 2025-07-11 to 2026-07-11 (12 months to the data freeze, UFC 329).
-- Roster: active-universe fighters at the freeze. The UNNEST list below is
--   generated by notebook 13 from active_universe.parquet (see the roster
--   snippet cell); paste its output here to refresh.-- Matching: MMA/UFC-context records only; distinctive-surname matching with a
--   common-surname blocklist to avoid roster-internal collisions.
-- Output columns: fighter, use_surname, gdelt_volume, gdelt_active_days.
-- Run once in the BigQuery console; result saved as gdelt_volume.csv 

WITH roster AS (
  SELECT name AS fighter
  FROM UNNEST([
    'jon jones',
    'islam makhachev',
    'ciryl gane',
    'shavkat rakhmonov',
    'ilia topuria',
    'alexander volkanovski',
    'khamzat chimaev',
    'dricus du plessis',
    'michael morales',
    'kamaru usman'
  ]) AS name
)
SELECT
  k.fighter,
  k.use_surname,
  COUNT(DISTINCT m.GKGRECORDID)          AS gdelt_volume,
  COUNT(DISTINCT DATE(m._PARTITIONTIME)) AS gdelt_active_days
FROM roster k
GROUP BY k.fighter, k.use_surname
ORDER BY gdelt_volume DESC
