WITH roster AS (
  SELECT name AS fighter
  FROM UNNEST([
    'jon jones',
    'islam makhachev',
    'ciryl gane',
    'shavkat rakhmonov',
    'ilia topuria',
    'alexander volkanovski',
    'khamzat chimaev',
    'dricus du plessis',
    'michael morales',
    'kamaru usman',
    'alex pereira',
    'merab dvalishvili',
    'stipe miocic',
    'justin gaethje',
    'carlos prates',
    'max holloway',
    'tom aspinall',
    'arman tsarukyan',
    'aljamain sterling',
    'charles oliveira',
    'movsar evloev',
    'alexander volkov',
    'umar nurmagomedov',
    'sean brady',
    'yaroslav amosov',
    'petr yan',
    'ian machado garry',
    'nassourdine imavov',
    'sean strickland',
    'magomed ankalaev',
    'diego lopes',
    'josh hokit',
    'carlos ulberg',
    'sergei pavlovich',
    'jiri prochazka',
    'robert whittaker',
    'jack della maddalena',
    "sean o'malley",
    'valentina shevchenko',
    'paddy pimblett',
    'leon edwards',
    'gabriel bonfim',
    'colby covington',
    'kayla harrison',
    'caio borralho',
    'dustin poirier',
    'zhang weili',
    'erin blanchfield',
    'joe pyfer',
    'brendan allen',
    'manon fiorot',
    'cory sandhagen',
    'tatiana suarez',
    'belal muhammad',
    'natalia silva',
    'curtis blaydes',
    'paulo costa',
    'lerone murphy',
    'song yadong',
    'rinat fakhretdinov',
    'michael page',
    'mario bautista',
    'mateusz gamrot',
    'ikram aliskerov',
    'israel adesanya',
    'quillan salkilld',
    'yousri belgaroui',
    'myktybek orolbai',
    'arnold allen',
    'yair rodriguez',
    'jailton almeida',
    'conor mcgregor',
    'kevin vallejos',
    'brian ortega',
    'jean silva',
    'grant dawson',
    'benoit saint denis',
    'anthony hernandez',
    'jan blachowicz',
    'mike malott',
    'reinier de ridder',
    'dominick reyes',
    'azamat murzakanov',
    'waldo cortes acosta',
    'vinicius oliveira',
    'manel kape',
    'mauricio ruffy',
    'pat sabatini',
    'muhammad mokaev',
    'alexandre pantoja',
    'gregory rodrigues',
    'david martinez',
    'joshua van',
    'jairzinho rozenstruik',
    'renato moicano',
    'joel alvarez',
    'rizvan kuniev',
    'farid basharat',
    'michael chiesa',
    'joaquin buckley',
    'jared cannonier',
    'rose namajunas',
    'deiveson figueiredo',
    'seokhyeon ko',
    'payton talbott',
    'jose aldo',
    'bogdan guskov',
    'daniel rodriguez',
    'tatsuro taira',
    'volkan oezdemir',
    'henry cejudo',
    'bryan battle',
    'bryce mitchell',
    'cam rowston',
    'ethyn ewing',
    'shara magomedov',
    'vicente luque',
    'bo nickal',
    'rafael fiziev',
    'beneil dariush',
    'jacobe smith',
    'mairon santos',
    'navajo stirling',
    'daniil donchenko',
    'neil magny',
    'brando pericic',
    'aiemann zahabi',
    'raoni barcelos',
    'kyoji horiguchi',
    'christian leroy duncan',
    'gilbert burns',
    'jamahal hill',
    'steve garcia',
    'kevin holland',
    'asu almabayev',
    'nathaniel wood',
    'rafael dos anjos',
    'randy brown',
    'king green',
    'derrick lewis',
    'jonathan micallef',
    'drakkar klose',
    'chepe mariscal',
    'stephen thompson',
    'roman dolidze',
    'daniel marcos',
    'alexa grasso',
    'montel jackson',
    'geoff neal',
    'aleksandar rakic',
    'jeremiah wells',
    'joanderson brito',
    'johnny walker',
    'luke riley',
    'gunnar nelson',
    'marlon vera',
    'brandon moreno',
    'manuel torres',
    'youssef zalal',
    'jasmine jasudavicius',
    'abus magomedov',
    'dan hooker',
    'virna jandiroba',
    'alexandr romanov',
    'serghei spivac',
    'kelvin gastelum',
    'marcus mcghee',
    'maycee barber',
    'uros medic',
    'jake matthews',
    'khalil rountree jr.',
    'chris weidman',
    'melquizael costa',
    'nursulton ruziboev',
    'mario pinto',
    'nikita krylov',
    'bia mesquita',
    'baisangur susurkaev',
    'ateba gautier',
    'luana santos',
    'rob font',
    'tyrell fortune',
    'julianna pena',
    'chris gutierrez',
    'josh emmett',
    'cub swanson',
    'diego ferreira',
    'marvin vettori',
    'fares ziam',
    'jalin turner',
    'khaos williams',
    'norma dumont',
    'nicolas dalby',
    'brandon royval',
    'santiago ponzinibbio',
    'damian pinas',
    'nurullo aliev',
    'jack hermansson',
    'dustin jacoby',
    'dooho choi',
    'chris duncan',
    'chris padilla',
    'pedro munhoz',
    'raquel pennington',
    'jonathan martinez',
    'gillian robertson',
    'elijah smith',
    'rafa garcia',
    'said nurmagomedov',
    'marcin tybura',
    'muslim salikhov',
    'jose delgado',
    'abdul rakhman yakhyaev',
    'yan xiaonan',
    'adrian yanez',
    'raul rosas jr.',
    'mackenzie dern',
    'ricky simon',
    'li jingliang',
    'lerryan douglas',
    'jim miller',
    'chris curtis',
    'ludovit klein',
    'calvin kattar',
    'mick parkin',
    'felipe lima',
    'giga chikadze',
    'alonzo menifield',
    'ketlen vieira',
    'william gomis',
    'dan ige',
    'patricio freire',
    'ignacio bahamondes',
    'charles jourdain',
    'ryan spann',
    'edson barboza',
    'taylor lapilus',
    'kai kara-france',
    'alexia thainara',
    'anthony smith',
    'jacob malkoun',
    'brunno ferreira',
    'alex perez',
    'ismail naurdiev',
    'jean matsumoto',
    'amir albazi',
    'drew dober',
    'cody haddon',
    'jakub wiklacz',
    'sam patterson',
    'david onama',
    'junyong park',
    'ailin perez',
    'edmen shahbazyan',
    'alexander hernandez',
    'iwo baraniewski',
    'wang cong',
    'roman kopylov',
    'andreas gustafsson',
    'victor valenzuela',
    'kyler phillips',
    'amanda lemos',
    'michael chandler',
    'tony ferguson',
    'vitor petrino',
    'valter walker',
    'michelle montague',
    'carla esparza',
    'denise gomes',
    'michel pereira',
    'ramazan temirov',
    'nasrat haqparast',
    'jessica andrade',
    'tom nolan',
    'jacqueline cavalcanti',
    'cezary oleksiejczuk',
    'carlos leal',
    'aleksandre topuria',
    'elizeu zaleski dos santos',
    'juan diaz',
    'gokhan saricam',
    'steve erceg',
    'sodiq yusuff',
    'marwan rahiki',
    'michal oleksiejczuk',
    'tracy cortez',
    'victor henry',
    'martin buday',
    'iasmin lucindo',
    'tabatha ricci',
    'andre muniz',
    'fatima kline',
    'marquel mederos',
    "casey o'neill",
    'tagir ulanbekov',
    'miranda maverick',
    'esteban ribovics',
    'ryan gandra',
    'melissa croden',
    'daniel santos',
    'mason jones',
    'talita alencar',
    'cody garbrandt',
    'jimmy crute',
    'joselyne edwards',
    'lance gibson jr.',
    'tallison teixeira',
    'irene aldana',
    'jean-paul lebosnoyani',
    'sean woodson',
    'tofiq musayev',
    'muhammad naimov',
    'davey grant',
    'yana santos',
    'darren elkins',
    'punahele soriano',
    'murtazali magomedov',
    'alden coria',
    'islam dulatov',
    'kaan ofli',
    'mateusz rebecki',
    'karine silva',
    'max griffin',
    'tecia pennington',
    'kaue fernandes',
    'mike davis',
    'jared gordon',
    'jaqueline amorim',
    'jack shore',
    'rinya nakamura',
    'zhang mingyang',
    'carlston harris',
    'ante delija',
    'ovince saint preux',
    'marina rodriguez',
    'eryk anders',
    'jonathan pearce',
    "da''mon blackshear",
    'charles radtke',
    'ty miller',
    'tommy gantt',
    'javid basharat',
    'rodrigo vera',
    'viviane araujo',
    'christian rodriguez',
    'luis felipe dias',
    'donghun choi',
    'damon jackson',
    'danny silva',
    'joe solecki',
    'loopy godinez',
    'levan chokheli',
    'themba gorimbo',
    'michael johnson',
    'billy elekana',
    'amanda ribas',
    'paul craig',
    'matheus nicolau',
    'rodrigo nascimento',
    'john castaneda',
    'shamil gaziev',
    'mansur abdul-malik',
    'morgan charriere',
    'tai tuivasa',
    'allan nascimento',
    'vinc pichel',
    'donte johnson',
    'keiichiro nakamura',
    'rodolfo bellato',
    'billy quarantillo',
    'mizuki',
    'kyle daukaus',
    'alex morono',
    'piera rodriguez',
    'tahir abdullayev',
    'manoel sousa',
    'rafael estevam',
    'modestas bukauskas',
    'joaquim silva',
    'phil rowe',
    'karol rosa',
    'karl williams',
    'brad tavares',
    'terrance mckinney',
    'jamall emmers',
    'claudio puelles',
    'ion cutelaba',
    'oban elliott',
    'joseph morales',
    'tommy mcmillen',
    'alessandro costa',
    'trey waters',
    'nazim sadykhov',
    'cody stamann',
    'court mcgee',
    'chase hooper',
    'kennedy nzechukwu',
    'jose ochoa',
    'matheus camilo',
    'gable steveson',
    'jordan leavitt',
    'imanol rodriguez',
    'jose delano',
    'oumar sy',
    'elves brener',
    'tim means',
    'julian erosa',
    'chidi njokuani',
    'gabriel santos',
    'mohammed usman',
    "lone''er kavanagh",
    'andre fili',
    'tim elliott',
    'lauren murphy',
    'jj aldrich',
    'macy chiasson',
    'eduarda moura',
    'miles johns',
    'thiago moises',
    'santiago luna',
    'marcio barbosa',
    'carli judice',
    'matt frevola',
    'shane collins',
    'alatengheili',
    'miesha tate',
    'stephanie luciano',
    'regina tarin',
    'yadier del valle',
    'serhiy sidey',
    'suyoung you',
    'aaron pico',
    'marco tulio',
    'douglas silva de andrade',
    'ramiz brahimaj',
    'charles johnson',
    'edgar chairez',
    'jhonata diniz',
    'andre lima',
    'clay guida',
    'dione barbosa',
    'bill algeo',
    'shanelle dyer',
    'alberto montes',
    'muin gafurov',
    'ismael bonfim',
    'gerald meerschaert',
    'benardo sopaj',
    'gauge young',
    'taiyilake nueraji',
    'jack jenkins',
    'rodolfo vieira',
    'hecher sosa',
    'ketlen souza',
    'kyle nelson',
    'jeremy stephens',
    'lawrence lui',
    'isaac dulgarian',
    'jai herbert',
    'javier reyes',
    'klaudia sygula',
    'hamdy abdelwahab',
    'jose souza',
    'angela hill',
    'matthew semelsberger',
    'rei tsuruya',
    'da woon jung',
    'niko price',
    'mark vologdin',
    'robert bryczek',
    'farman hasanov',
    'victor hugo',
    'charlie campbell',
    'trey ogden',
    'nora cornolle',
    'jafel filho',
    'cesar almeida',
    'andre petroski',
    'thomas petersen',
    'gabe green',
    'daniel zellhuber',
    'song kenan',
    'mantas kondratavicius',
    'melissa gatto',
    'bassil hafez',
    'nyamjargal tumendemberel',
    'jamie mullarkey',
    'jamey-lyn horth',
    'austin bashi',
    'eric mcconico',
    'trevin giles',
    'kevin jousset',
    'daria zhelezniakova',
    'louie sutherland',
    'nate landwehr',
    'francis marshall',
    'tanner boser',
    'fernando padilla',
    'carlos vera',
    'hyder amil',
    'sam hughes',
    'mayra bueno silva',
    'abdul razak alhassan',
    'julia polastri',
    'yanal ashmouz',
    'chelsea chandler',
    'josefine knutsson',
    'marc-andre barriault',
    'dustin stoltzfus',
    'armen petrosyan',
    'losene keita',
    'mitch raposo',
    'daniel pineda',
    'sumudaerji',
    'veronica hardy',
    'axel sola',
    'nikolas motta',
    'pannie kianzad',
    'bekzat almakhan',
    'ricky glenn',
    'cody brundage',
    'bruno silva',
    'hyunsung park',
    'steven asplund',
    'colby thicknesse',
    'josh culibao',
    'malcolm wellmaker',
    'joosang yoo',
    'saygid izagakhmaev',
    'kai asakura',
    'changho lee',
    'andrea lee',
    'ricardo ramos',
    'roosevelt roberts',
    'john garza',
    'brian kelleher',
    'cameron saaiman',
    'rongzhu',
    'caolan loughran',
    'zach reese',
    'luana carolina',
    'damir hadzovic',
    'austin vanderford',
    'alice pereira',
    'nikolay veretennikov',
    'azamat bekoev',
    'preston parsons',
    'tresean gore',
    'melissa mullins',
    'xiao long',
    'evan elder',
    'uran satybaldiev',
    'ariane da silva',
    'jeisla chaves',
    'melsik baghdasaryan',
    'karolina kowalkiewicz',
    'loma lookboonmee',
    'loik radzhabov',
    'kody steele',
    'montse rendon',
    'wes schultz',
    'jeongyeong lee',
    'kai kamaka iii',
    'kron gracie',
    'jesus aguilar',
    'ange loosa',
    'alice ardelean',
    'luana pinheiro',
    'denzel freeman',
    'justin tafa',
    'cristian quinonez',
    'jamal pogues',
    'clayton carpenter',
    'yazmin jauregui',
    'trevor peek',
    'john yannis',
    'bogdan grad',
    'isaac thomson',
    'julia avila',
    'guram kutateladze',
    'gabriella fernandes',
    'ryan loder',
    'bruno lopes',
    'cody durden',
    'christian edwards',
    'andrey pulyaev',
    'guilherme pat',
    'jared gooden',
    'mickey gall',
    'aoriqileng',
    'cory mckenna',
    'danny barlow',
    'matt schnell',
    'marcus buchecha',
    'jackson mcvey',
    'shi ming',
    'tainara lisboa',
    'lucas rocha',
    'garrett armfield',
    'abdul-kareem al-selwady',
    'felipe franco',
    'jake hadley',
    'ronaldo rodriguez',
    'lando vannata',
    'torrez finney',
    'ottman azaitar',
    'timmy cuamba',
    'gaston bolanos',
    'alibi idiris',
    'djorden santos',
    'magomed gadzhiyasulov',
    'josiane nunes',
    'zachary scroggin',
    'julius walker',
    'francisco prado',
    "don''tale mayes",
    'chris barnett',
    'molly mccann',
    'brad katona',
    'vanessa demopoulos',
    'billy ray goff',
    'ramon taveras',
    'patchy mix',
    'lucas almeida',
    'felipe dos santos',
    'ozzy diaz',
    'ivan erslan',
    'josiah harrell',
    'adrian luna martinetti',
    'alvin hines',
    'felipe bunes',
    'michael aswell jr.',
    'kevin borjas',
    'marcin prachnio',
    'ihor potieria',
    'nathan fletcher',
    'ernesta kareckaite',
    'cody gibson',
    'austin hubbard',
    'carlos hernandez',
    'darrius flowers',
    'ibo aslan',
    'vince morales',
    'dakota hope',
    'ding meng',
    'bruna brasil',
    'dusko todorovic',
    'nicolle caliari',
    'quang le',
    'yizha',
    'theodor berggren',
    'mariya agapova',
    'chad anheliger',
    'sulangrangbo',
    'bolaji oki',
    'cameron smotherman',
    'steven nguyen',
    'tereza bleda',
    'ariane carnelossi',
    'seungwoo choi',
    'dom mar fan',
    'mark choinski',
    'dan argueta',
    'adam fugitt',
    'viacheslav borshchev',
    'ode osbourne',
    'robert ruchala',
    'priscila cachoeira',
    'victor altamirano',
    'elise reed',
    'viktoriia dudakova',
    'puja tomar',
    'gianni vazquez',
    "tre''ston vines",
    'herbert burns',
    'josh fremd',
    'jose johnson',
    'kurt holobaugh',
    'brendson ribeiro',
    'xiong jingnan',
    'robelis despaigne',
    'gilbert urbina',
    'otari tanzilovi',
    'marek bujlo',
    'junior tafa',
    'juliana miller',
    'jimmy flick',
    'sangwook kim',
    'allen frye jr.',
    'azat maksum',
    'kurtis campbell',
    'julian marquez',
    'robert valentin',
    'ollie schmid',
    'irina alekseeva',
    'julija stoliarenko',
    'jessica penne',
    'baergeng jieleyisi',
    'lucas brennan',
    'rolando bedoya',
    'tuco tokkos',
    'pedro falcao',
    'luke fernandez',
    'maheshate',
    'luan lacerda',
    'jarno errens',
    'patricio pitbull',
    'gabriel miranda',
    'mandel nallo',
    'lucie pudilova',
    'jefferson nascimento',
    'lukasz brzeski',
    'zygimantas ramaska',
    'feng xiaocan',
    'sebastian szalay',
    'aj cunningham',
    'polyana viana',
    'cj vergara',
    'lucas alexander',
    'leon shahbazyan',
    'max gimenis',
    'jordan vucenic',
    'rafael cerqueira',
    'shem rock',
    'sedriques dumas',
    'kiru sahota',
    'yisak lee',
    'shauna bannon',
    'zhu kangjie',
    'artur minev',
    'rhys mckee',
    'james llontop',
    'tamires vidal',
    'mitch ramirez',
    'rodrigo sezinando',
    'westin wilson',
    'luis gurule',
    'dennis buzukja',
    'diyar nurgozhay',
    'melissa martinez',
    'kaynan kruschewsky',
    'ricky turcios',
    'kyle prepolec',
    'jeka saragih',
    'denis tiuliulin',
    'angel pacheco',
    'anshul jubli',
    'daniel barez',
    'ivana petrovic',
    'caio machado',
    'austen lane',
    'dylan budka',
    'brendon marotte',
    'terrance saeteurn',
    'roberto romero',
    'harry hardwick',
    'nick klein',
    'eric nolan',
    'toshiomi kazama',
    'ben johnston',
    'victoria leonardo',
    'cortavious romious',
    'alex reyes',
    'diana belbita',
    'ravena oliveira',
    'hailey cowan',
    'jamie siraj',
    'yuneisy duben',
    'rafael cerquiera',
    'rayanne dos santos',
    'elisha ellison',
    'erik silva',
    'antonio trocoli',
    'brogan walker',
    'kevin christian',
    'montserrat conejo ruiz',
    'rafael tobias',
    'manolo zecchini',
    'julien leblanc',
    'josias musasa',
    'kris moutinho',
    'sean sharaf',
    'stewart nicoll',
    'daniel frunza',
    'kiefer crosbie',
    'istela nunes',
    'charalampos grigoriou',
    'jose daniel medina',
    'saimon oliveira',
    'mohammad yahya',
    'connor matthews'
  ]) AS name
),
clean AS (
  SELECT fighter,
         LOWER(TRIM(REGEXP_REPLACE(fighter, r"['\.]", ''))) AS full_key
  FROM roster
),
tokens AS (
  -- every token of every roster name, so we can tell if a surname also appears as someone's first name
  SELECT tok, COUNT(*) AS tok_uses
  FROM clean, UNNEST(SPLIT(full_key, ' ')) AS tok
  GROUP BY tok
),
keys AS (
  SELECT c.fighter, c.full_key,
         ARRAY_REVERSE(SPLIT(c.full_key, ' '))[OFFSET(0)] AS surname_key
  FROM clean c
),
matchable AS (
  SELECT k.fighter, k.full_key, k.surname_key,
         ( LENGTH(k.surname_key) >= 6
           AND t.tok_uses = 1                                   -- appears nowhere else on the roster, any position
           AND k.surname_key NOT IN (                           -- common names MMA coverage will contain anyway
             'alexander','anderson','barbosa','bautista','brown','campbell','carvalho','castillo',
             'christian','collins','cordeiro','costa','davis','edwards','ferreira','fernandes',
             'freitas','garcia','gomes','gonzalez','gordon','green','harris','henry','hernandez',
             'holland','jackson','johnson','jones','marshall','martin','martinez','mcgregor',
             'mendes','miller','mitchell','moreno','morales','murphy','nelson','oliveira','parker',
             'pereira','peterson','ramos','reyes','rodrigues','rodriguez','santos','silva','simon',
             'smith','taylor','thompson','turner','walker','williams','wilson','young'
           )
         ) AS use_surname
  FROM keys k
  JOIN tokens t ON t.tok = k.surname_key
),
mma AS (
  SELECT GKGRECORDID, _PARTITIONTIME, LOWER(V2Persons) AS persons
  FROM `gdelt-bq.gdeltv2.gkg_partitioned`
  WHERE _PARTITIONTIME >= TIMESTAMP("2025-07-11")
    AND _PARTITIONTIME <  TIMESTAMP("2026-07-11")
    AND V2Persons IS NOT NULL
    AND (
         LOWER(V2Organizations)    LIKE '%ultimate fighting%'
      OR LOWER(DocumentIdentifier) LIKE '%mma%'
      OR LOWER(DocumentIdentifier) LIKE '%ufc%'
      OR LOWER(SourceCommonName)   LIKE '%mma%'
    )
)
SELECT
  k.fighter,
  k.use_surname,
  COUNT(DISTINCT m.GKGRECORDID)          AS gdelt_volume,
  COUNT(DISTINCT DATE(m._PARTITIONTIME)) AS gdelt_active_days
FROM matchable k
LEFT JOIN mma m
  ON ( k.use_surname AND REGEXP_CONTAINS(m.persons, CONCAT(r'\b', k.surname_key, r'\b')) )
  OR REGEXP_CONTAINS(m.persons, CONCAT(r'\b', k.full_key, r'\b'))
GROUP BY k.fighter, k.use_surname
ORDER BY gdelt_volume DESC
